# Generated by Django 4.1.3 on 2022-12-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=150)),
                ("date", models.DateField(auto_now_add=True)),
                ("done", models.BooleanField(default=False)),
            ],
        ),
    ]
